permissions:
  contents: write

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      
      - name: Build graph
        run: ${PWD}/make_graph.sh
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H%M%S')" >> $GITHUB_ENV
        shell: bash
      - name: Create GH release
        run: gh release create $NOW graph.json spritesheet.png
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash